### ISSUE TITLE
A bug appears during training

### ISSUE THREAD

**Issue by RS-Bugmaker** [ljf012/GNN-DSR#1]
Hello, when I retrain the model, what is the cause of such errors after running hundreds of epochs?
RuntimeError: The expanded size of the tensor (29) must match the existing size (30) at non-singleton dimension 0. Target sizes : [29, 3]. Tensor size: [30, 3]

**Comment by ljf012** [comment]
This problem may be caused by the data mismatch, for example, some users may have interacted with less than 30 items. I remember that I have already solved this problem by using 'drop_last=True' in **DataLoader** from **main.py**.

Can you describe the bug in more detail? On Epinions or Ciao?

**Comment by RS-Bugmaker** [comment]
At first, I downloaded the original Ciao dataset, and then used preprocess.py processed this data set. I changed the number of epochs trained to 2000, and then used (python main.py) to train the model. There was no problem in the first few hundred rounds of training, and this bug appeared in about six or seven hundred rounds.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ljf012/GNN-DSR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月15日(星期二) 下午4:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ljf012/GNN-DSR] A bug appears during training (Issue #1)





 
This problem may be caused by the data mismatch, for example, some users may have interacted with less than 30 items. I remembered that I had already solve this problem by using 'drop_last=True' in DataLoader from main.py.
 
Can you describe the bug in more detail? On Epinions or Ciao?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ljf012** [comment]
This is a rather strange bug that I have never encountered yet. Did you encounter this bug with the processed data provided? Besides, it does not need to train so many epochs, the loss should have converged before then.

**Comment by RS-Bugmaker** [comment]
Sorry, I can't download the data provided so I choose to download the original data set for processing. I try to use other methods to download the data provided for experiments. Also, I want to ask about how many rounds of training the model needs to converge.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ljf012/GNN-DSR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月15日(星期二) 下午5:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ljf012/GNN-DSR] A bug appears during training (Issue #1)





 
This is a rather strange bug that I have never encountered yet. Did you encounter this bug with the processed data provided? Besides, it does not need to train so many epochs, the loss should have converged before then.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ljf012** [comment]
This may be the network problem causing the download to fail. You can try to download with [GitHub Desktop](https://desktop.github.com/). 
The 20 epochs we used can achieve a good result.
