### ISSUE TITLE
大文件下载的问题

### ISSUE THREAD

**Issue by zhenyuZ-HUST** [ljf012/GNN-DSR#3]
作者你好，我在git lfs clone项目的时候显示This repository is over its data quota，不知能否麻烦您提供下datasets和weights文件的其他下载方式？

**Comment by ljf012** [comment]
已经上传到谷歌云盘了，可以在Readme里查看。

**Comment by zhenyuZ-HUST** [comment]
感谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月31日(星期四) 晚上8:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ljf012/GNN-DSR] 大文件下载的问题 (Issue #3)





 
已经上传到谷歌云盘了，可以在Readme里查看。
