### ISSUE TITLE
训练出现tensor size不匹配

### ISSUE THREAD

**Issue by zhenyuZ-HUST** [ljf012/GNN-DSR#4]
你好，我在使用云盘的数据集执行python main.py时，在某些批次的训练当中会出现tensor大小不匹配的情况：
Traceback (most recent call last):
  File "main.py", line 196, in <module>
    main()
  File "main.py", line 96, in main
    trainForEpoch(train_loader, model, optimizer, epoch, args.epoch, criterion, log_aggr = 100)
  File "main.py", line 135, in trainForEpoch
    for i, (uids, iids, ratings, tids, u_items, u_users, u_users_items, i_users, i_items, i_items_users) in tqdm(enumerate(train_loader), total=len(train_loader)):
  File "C:\Users\92585\Anaconda3\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "C:\Users\92585\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\92585\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\92585\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "C:\Users\92585\Desktop\graduation\article with code\GNN-DSR-master\GNN-DSR-master\utils.py", line 179, in collate_fn
    i_item_user_pad[i, j, :len(iu), :] = torch.LongTensor(iu)
RuntimeError: The expanded size of the tensor (21) must match the existing size (27) at non-singleton dimension 0.  Target sizes: [21, 3].  Tensor sizes: [27, 3]
不知道该如何解决，并且在两个数据集上都存在该情况。

**Comment by zhenyuZ-HUST** [comment]
问题似乎是源自于utils.py文件145行计算i_users_maxlen变量时，实际上数据集当中的最长长度大于该变量，导致初始化u_item_pad时预留大小不足，我尝试直接指定i_users_maxlen为较大变量，这样程序可以正常运行。

**Comment by ljf012** [comment]
确实是数据长度不匹配的问题。你用的这个办法可以，也可以尝试裁剪掉那些超出长度的变量使得他们匹配。

但这个bug很奇怪，就像[issues1](https://github.com/ljf012/GNN-DSR/issues/1#issuecomment-1067691211)所说的，我通过这个方法解决了并且之后的实验中都没遇到这个问题，刚才又训练了一次也没问题。
![QQ截图20220401145143](https://user-images.githubusercontent.com/37583355/161214245-ae9d9a6a-f9a7-4605-9278-36295c2401da.png)

**Comment by ZQSong1997** [comment]
> 问题似乎是源自于utils.py文件145行计算i_users_maxlen变量时，实际上数据集当中的最长长度大于该变量，导致初始化u_item_pad时预留大小不足，我尝试直接指定i_users_maxlen为较大变量，这样程序可以正常运行。

您好，我在ciao和Epinions数据集中也遇到了这个问题。
我将utils.py文件的第96行中的i_users_len.append(min(len(i_users_i), truncate_len_i)) 中的min改为max后成功解决了ciao数据集上的报错问题。将i_users_len.append(min(len(i_users_i), truncate_len_i)) 和第42行u_items_len.append(min(len(u_items_u), truncate_len))中的min同时改为max后解决了Epinions数据集上的报错问题。
可是这样存在一个很大的缺点，内存占用急剧增大，特别是在Epinions数据集上batchsize设为8在11GB的GPU上都不够跑。
所以想请教一下您是如何解决的呢？谢谢！

**Comment by zhenyuZ-HUST** [comment]
已经是很久以前的事情了，我也记不太清了，我应该只是人工设定了i_users_maxlen的值为一个比较大的值，这个值您可以逐步增大来取，来使得正常运行并且浪费空间尽量小。您的这种方法我确实没有试过。

**Comment by zhenyuZ-HUST** [comment]
> > 问题似乎是源自于utils.py文件145行计算i_users_maxlen变量时，实际上数据集当中的最长长度大于该变量，导致初始化u_item_pad时预留大小不足，我尝试直接指定i_users_maxlen为较大变量，这样程序可以正常运行。
> 
> 您好，我在ciao和Epinions数据集中也遇到了这个问题。 我将utils.py文件的第96行中的i_users_len.append(min(len(i_users_i), truncate_len_i)) 中的min改为max后成功解决了ciao数据集上的报错问题。将i_users_len.append(min(len(i_users_i), truncate_len_i)) 和第42行u_items_len.append(min(len(u_items_u), truncate_len))中的min同时改为max后解决了Epinions数据集上的报错问题。 可是这样存在一个很大的缺点，内存占用急剧增大，特别是在Epinions数据集上batchsize设为8在11GB的GPU上都不够跑。 所以想请教一下您是如何解决的呢？谢谢！

已经是很久以前的事情了，我也记不太清了，我应该只是人工设定了i_users_maxlen的值为一个比较大的值，这个值您可以逐步增大来取，来使得正常运行并且浪费空间尽量小。您的这种方法我确实没有试过。

**Comment by ZQSong1997** [comment]
> > > 问题似乎是源自于utils.py文件145行计算i_users_maxlen变量时，实际上数据集当中的最长长度大于该变量，导致初始化u_item_pad时预留大小不足，我尝试直接指定i_users_maxlen为较大变量，这样程序可以正常运行。
> > 
> > 
> > 您好，我在ciao和Epinions数据集中也遇到了这个问题。 我将utils.py文件的第96行中的i_users_len.append(min(len(i_users_i), truncate_len_i)) 中的min改为max后成功解决了ciao数据集上的报错问题。将i_users_len.append(min(len(i_users_i), truncate_len_i)) 和第42行u_items_len.append(min(len(u_items_u), truncate_len))中的min同时改为max后解决了Epinions数据集上的报错问题。 可是这样存在一个很大的缺点，内存占用急剧增大，特别是在Epinions数据集上batchsize设为8在11GB的GPU上都不够跑。 所以想请教一下您是如何解决的呢？谢谢！
> 
> 已经是很久以前的事情了，我也记不太清了，我应该只是人工设定了i_users_maxlen的值为一个比较大的值，这个值您可以逐步增大来取，来使得正常运行并且浪费空间尽量小。您的这种方法我确实没有试过。

好的，感谢您的回复！
