### ISSUE TITLE
关于pickle时报错的问题

### ISSUE THREAD

**Issue by TcGgggu** [ljf012/GNN-DSR#7]
作者您好！在下载了代码包安装了依赖之后，运行python main.py --test出现如下错误：
![image](https://user-images.githubusercontent.com/76771756/207205973-9c9125fc-19bf-4267-94f9-6450a9791265.png)
从报错行这里找到在main.py的这里
![image](https://user-images.githubusercontent.com/76771756/207206188-22054389-ba31-4f58-9f9b-fafe3d9bf020.png)
打开相应文件是这个
![image](https://user-images.githubusercontent.com/76771756/207206267-5a2d0572-e0c9-417a-bd7d-891f2e8765ae.png)
请教大佬这个报错怎么解决一下呢 感激不尽

**Comment by ljf012** [comment]
pickle读取的问题，可能是编码不一样，但我没遇到过，你可以试试用pickle.loads()看能不能读取。
还不行的话就试试用 [preprocess.py](https://github.com/ljf012/GNN-DSR/blob/master/preprocess.py)重新生成pkl文件再读取。

**Comment by TcGgggu** [comment]
> pickle读取的问题，可能是编码不一样，但我没遇到过，你可以试试用pickle.loads()看能不能读取。 还不行的话就试试用 [preprocess.py](https://github.com/ljf012/GNN-DSR/blob/master/preprocess.py)重新生成pkl文件再读取。

感谢大佬！已经解决
